
/*
CREATE DATABASE VRS;

USE VRS;

CREATE TABLE PERSON(
    PERSON_ID VARCHAR(20) PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DOB DATE NOT NULL,
    GENDER CHAR(1) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    CONTACT_NO VARCHAR(12),
    ROLE VARCHAR(10) NOT NULL
);

DESC PERSON;

CREATE TABLE VEHICLE(
    VEHICLE_ID VARCHAR(20) PRIMARY KEY NOT NULL,
    VEHICLE_NAME VARCHAR(50) NOT NULL,
    VEHICLE_TYPE VARCHAR(4) NOT NULL,
    VEHICLE_NO VARCHAR(12) NOT NULL,
    VEHICLE_KMS INT,
    VEHICLE_SERVICED BOOLEAN NOT NULL,
    VEHICLE_AVAILABILTY BOOLEAN NOT NULL,
    VEHICLE_RENT_COUNT INT,
);

DESC VEHICLE;
CREATE TABLE BILL(
    BILL_ID VARCHAR(20) PRIMARY KEY NOT NULL,
    BILL_DATE DATE NOT NULL,
    ADDITIONAL_KMS_AMT INT NOT NULL,
    VEHICLE_DAMAGE VARCHAR(5) NOT NULL,
    VEHICLE_DAMAGE_AMT INT NOT NULL,
    TOTAL_AMT INT NOT NULL,
    RETURNED_AMT INT NOT NULL,
    PERSON_ID VARCHAR(20) NOT NULL,
    VEHICLE_ID VARCHAR(20) NOT NULL,
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID)
);

DESC BILL;
CREATE TABLE BORROW(
    BORROW_ID VARCHAR(20) PRIMARY KEY NOT NULL,
    BORROW_DATE DATETIME NOT NULL,
    RETURN_DATE DATETIME NOT NULL,
    DEPOSIT INT NOT NULL,
    EXTENSION_COUNT INT NOT NULL DEFAULT 0,
    PERSON_ID VARCHAR(20) NOT NULL,
    VEHICLE_ID VARCHAR(20) NOT NULL,
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID)
);
DESC BORROW;

DESC PERSON;

DROP FOREIGN KEY vehicle_ibfk_1;
ALTER TABLE VEHICLE
DROP COLUMN PERSON_ID;
DESC VEHICLE;
*/ 
ALTER TABLE VEHICLE
MODIFY COLUMN VEHICLE_NO VARCHAR(25);
